version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    networks:
      - nest-micro

  service1:
    build: ./service1
    image: nest-service1
    container_name: service1
    environment:
      QUEUE_IP: amqp://rabbitmq:5672
    networks:
      - nest-micro

  service2:
    build: ./service2
    image: nest-service2
    container_name: service2
    environment:
      QUEUE_IP: amqp://rabbitmq:5672
    networks:
      - nest-micro

  gateway:
    build: ./gateway
    image: nest-gateway
    container_name: gateway
    environment:
      QUEUE_IP: amqp://rabbitmq:5672
    ports:
      - 3000:3000
    networks:
      - nest-micro

networks: 
  nest-micro: