version: "3"
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - nest-micro

  service1:
    build: ./service1
    image: nest-service1
    container_name: service1
    environment:
      QUEUE_IP: redis
    networks:
      - nest-micro

  service2:
    build: ./service2
    image: nest-service2
    container_name: service2
    environment:
      QUEUE_IP: redis
    networks:
      - nest-micro

  gateway:
    build: ./gateway
    image: nest-gateway
    container_name: gateway
    environment:
      QUEUE_IP: redis
    ports:
      - 3000:3000
    networks:
      - nest-micro

networks: 
  nest-micro: