apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
  namespace: micro
spec:
  replicas: 1
  selector:
    app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: pedroaal04/nest-gateway:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: "production"
        - name: QUEUE_IP
          value: 10.43.7.222
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-lb
  namespace: micro
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 3000
      name: http