apiVersion: v1
kind: ReplicationController
metadata:
  name: service2
  namespace: micro
spec:
  replicas: 1
  selector:
    app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: pedroaal04/nest-service2:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: "production"
        - name: QUEUE_IP
          value: 10.43.7.222
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi