FROM node:16.15.0 AS BASEIMAGE

WORKDIR /src
COPY package*.json ./
RUN yarn
COPY . .
RUN yarn prebuild && yarn build && npm prune --production

FROM node:16.15.0

WORKDIR /src
ENV TZ=America/Guayaquil
COPY --from=BASEIMAGE /src/dist /src/dist
COPY --from=BASEIMAGE /src/node_modules /src/node_modules
EXPOSE 3000

CMD ["node", "dist/main.js"]